### ISSUE TITLE
glob 'module' object is not callable

### ISSUE THREAD

**Issue by roomo7time** [Heumi/BEGAN-tensorflow#3]
On 55-th line in op_base.py, 
`data = sorted(glob(os.path.join(data_path, "*.*")))`
I get the following error,
```
Traceback (most recent call last):
  File "/home/jay/pycharm-2017.1.1/helpers/pydev/_pydevd_bundle/pydevd_exec.py", line 3, in Exec
    exec exp in global_vars, local_vars
  File "<string>", line 1, in <module>
TypeError: 'module' object is not callable
```

I followed your instructions correctly.

Is it because I'm using Ubuntu or Pycharm?

**Comment by roomo7time** [comment]
I replaced on line 55 `glob` by `glob.glob`. It is running now, printing
```
Epoch: [ 0] [  90/9765] time: 39.6212, loss: 0.2288, loss_g: 0.0163, loss_d: 0.2126, d_real: 0.2127, d_fake: 0.0163, kt: 0.00630969, M: 0.28146463
Epoch: [ 0] [  91/9765] time: 40.0160, loss: 0.2423, loss_g: 0.0246, loss_d: 0.2177, d_real: 0.2178, d_fake: 0.0246, kt: 0.00637223, M: 0.28034942
Epoch: [ 0] [  92/9765] time: 40.4084, loss: 0.2675, loss_g: 0.0328, loss_d: 0.2348, d_real: 0.2349, d_fake: 0.0328, kt: 0.00643345, M: 0.29616759
Epoch: [ 0] [  93/9765] time: 40.7987, loss: 0.2332, loss_g: 0.0360, loss_d: 0.1972, d_real: 0.1974, d_fake: 0.0360, kt: 0.00647640, M: 0.24030239
Epoch: [ 0] [  94/9765] time: 41.1843, loss: 0.2442, loss_g: 0.0334, loss_d: 0.2108, d_real: 0.2110, d_fake: 0.0334, kt: 0.00652736, M: 0.26191271
```

**But I'm still not so sure if it is okay.** Could you help please?

**Comment by hmi88** [comment]
I also use Ubuntu and Pycharm. When I change this project to python3.5, I also got this error. I think 'glob.glob' is solution. I changed my repo. Thank you!
